- type: project
  description: "Genetic Enhancement of FHB Resistance in Barley"
  date: 2024-08-12
  image: /images/IMG_background_magic.JPG
  repo:
  tags:
    - open science
    - collaboration
  
  
